#!/usr/bin/env python3
"""Export deterministic JSON Schema from the authoritative Pydantic models."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from saas_preflight.affiliate_partner_ledger import AffiliatePartnerLedger
from saas_preflight.ai_routing import (
    EvaluatedModelRoute,
    ModelRouterPolicy,
    ModelRoutingEvaluation,
    ModelRoutingRequest,
)
from saas_preflight.control_cycle import (
    ControlConfig,
    ControlReport,
    ControlTrustStore,
    Ed25519VerificationKey,
    GoldReportAttestation,
    ReleaseDecisionAttestation,
    SchedulerHeartbeat,
    ServingLease,
)
from saas_preflight.external_actions import (
    ActionExecutionClaim,
    ActionJournalEntry,
    ActionJournalReport,
    ActionReceipt,
    ActionRevocation,
    ControllerExecutionGrant,
    ExternalActionPolicy,
    ExternalActionRequest,
    ExternalActionTargetRule,
    ExternalActionTrustStore,
    HumanExecutionApproval,
)
from saas_preflight.editorial_input import (
    CategoryExpansionInput,
    EditorialArticleInput,
    HumanEditorialNumericField,
)
from saas_preflight.goldset import CandidateBatch, GoldSetReport, HumanGoldSet
from saas_preflight.growth_system import (
    ClaimEvidenceLink,
    ConditionalActivationEvaluation,
    ConditionalActivationInput,
    ContentBrief,
    ContentDerivative,
    CtaHealthEvaluation,
    CtaHealthInput,
    DerivativeBundle,
    EditorialDraft,
    EditorialEvaluation,
    EditorialPackage,
    FeedbackBatch,
    FunnelEvent,
    GrowthIdentity,
    HumanPolicyDecisionReceipt,
    InitiativeAssessment,
    InitiativePortfolio,
    InitiativeProposal,
    KpiScorecard,
    LearningGoldCase,
    LearningGoldSet,
    MetricDefinition,
    OperationsKpiInput,
    PolicyMemo,
    PromptModelRun,
    PromptRunLedger,
    SemanticFact,
    SemanticSnapshot,
)
from saas_preflight.initial_learning_quality import (
    InitialLearningAttestation,
    InitialLearningDatasetProfile,
    InitialLearningQualityBundle,
    InitialLearningQualityCheck,
    InitialLearningQualityPolicy,
    InitialLearningQualityReport,
    InitialLearningTrustStore,
    InitialLearningVerificationKey,
)
from saas_preflight.launch_handoff import (
    LaunchArtifactComponent,
    LaunchGateReceipt,
    LaunchHandoffBundle,
    LaunchHandoffPlan,
    LaunchHandoffPolicy,
    LaunchHandoffReport,
    LaunchHandoffRequirement,
    LaunchHandoffTrustStore,
)
from saas_preflight.launch_semantics import (
    AffiliateSemanticPacket,
    DeploymentPublicationSemanticPacket,
    DeploymentReadinessRecord,
    GoldSemanticPacket,
    LaunchSemanticAuthorityPins,
    LaunchSemanticComponent,
    LaunchSemanticEvaluation,
    LaunchSemanticGateEvaluation,
    LaunchSemanticPacket,
    LaunchSemanticScope,
    MeasurementSemanticPacket,
    ProductionSemanticPacket,
    PublicationReadinessRecord,
    RightsSemanticPacket,
)
from saas_preflight.models import EvidencePointer, SourcePolicy, VendorPlan
from saas_preflight.operations_activity import (
    DailyDerivedOperations,
    DerivedOperationsActivitySummary,
    HumanActivityEvent,
    MonthlyOperatingTco,
    OperationalCostPolicy,
    OperationsActivityBatch,
    ResourceUsageEvent,
    RoleLaborRate,
    RoutineTaskDefinition,
    RoutineTaskExecution,
    ScheduledRoutineTask,
    TaskActivityCoverage,
)
from saas_preflight.measurement import (
    CohortSummaryBatch,
    DemandSummaryBatch,
    OperationsSummaryBatch,
)
from saas_preflight.measurement_integrity import (
    CohortIntegrityBatch,
    CoveragePartition,
    CurrentTransaction,
    DemandIntegrityBatch,
    FaultExercise,
    FaultRequirement,
    LogicalJobRun,
    MeasurementBundleIndex,
    MeasurementBoundDossier,
    MeasurementAuthorityPins,
    MeasurementIntegrityReport,
    MeasurementPolicy,
    MeasurementReconciliationFacts,
    MeasurementRulePins,
    MeasurementRunDefinition,
    MeasurementTrustStore,
    OperationsIntegrityBatch,
    PayoutStatement,
    ProducerAttestation,
    ProducerCoverage,
    SignedMeasurementRunPlan,
)
from saas_preflight.mangools_export import (
    MangoolsDemandSafeSummary,
    MangoolsSlateDemandSafeSummary,
)
from saas_preflight.preview import PreviewPage
from saas_preflight.repository_acceptance import (
    HumanRepositoryAcceptance,
    RepositoryAcceptanceAuthorityPins,
    RepositoryAcceptanceAuthorityBundle,
    RepositoryAcceptancePolicy,
    RepositoryAcceptanceReceiptChain,
    RepositoryAcceptanceReport,
    RepositoryAcceptanceTrustStore,
    RepositoryCandidateManifest,
    RepositoryFileDigest,
    RepositoryVerificationEvidenceBundle,
    RepositoryVerificationFact,
    RepositoryVerificationAttestation,
    RepositoryVerificationRequirement,
)
from saas_preflight.production_consumer import (
    GlobalStopSnapshot,
    HumanGlobalStopReset,
    ProductionConsumptionRequest,
    ProductionConsumptionResult,
    ProductionConsumerClockRequest,
    ProductionConsumerPolicy,
    ProductionConsumerTrustStore,
    ProductionAuthorityRootRequest,
    SignedProductionAuthorityRoots,
    SignedProductionConsumerClockAttestation,
    ProviderDispatchToken,
    ProviderProbeReceipt,
    ProviderResultReceipt,
    ProviderTargetRule,
)
from saas_preflight.production_readiness import (
    BackupRestoreFacts,
    EgressAllowlistFacts,
    ExternalMonotonicAnchorFacts,
    IndependentReadbackFacts,
    KmsIdentitySeparationFacts,
    ProductionBootstrapAuthorization,
    ProductionHumanEnvironmentApproval,
    ProductionIntegrationEvidence,
    ProductionIntegrationEvidenceBundle,
    ProductionIntegrationPlan,
    ProductionIntegrationPolicy,
    ProductionIntegrationRequirement,
    ProductionIntegrationTrustStore,
    ProductionReadinessAuthorityPins,
    ProductionReadinessReport,
    ProductionReconciliationFacts,
    ProductionReconciliationRecord,
    ProductionReconciliationReport,
    ProductionTcoQaAttestation,
    ProviderConditionalMutationFacts,
    ProviderIdempotencyRetentionFacts,
    ProviderReceiptLookupFacts,
    RollbackDisableFacts,
    SharedDurableStoreFencingFacts,
    TrustedClockFacts,
)
from saas_preflight.preflight import BusinessDossier
from saas_preflight.readiness_builder import (
    AffiliateDecisionBatch,
    CohortEvidence,
    DemandEvidence,
    OperationsEvidence,
)
from saas_preflight.release_assurance import (
    AssuranceEvidence,
    AssuranceEvidenceBundle,
    AssurancePolicy,
    AssuranceRequirement,
    DeterminismFacts,
    IntegrityFacts,
    LocalAssuranceAttestation,
    LocalAssuranceReport,
    PublicReleaseApprovalAttestation,
    ReleaseAssuranceReport,
    ReleaseAuthorization,
    ReviewFacts,
    RouteAssuranceFacts,
    ScanFacts,
    TestSuiteFacts,
)
from saas_preflight.settlement_amendment import (
    OriginalSettlementBinding,
    PartnerSettlementAmount,
    SettlementAmendmentAuthorityPins,
    SettlementAmendmentEvaluation,
    SettlementAmendmentPolicy,
    SettlementAmendmentTrustStore,
    SettlementCompletenessAttestation,
    SettlementCompletenessCoverage,
    SettlementPayoutAdjustment,
    SettlementStatusChange,
    SignedSettlementAmendment,
)
from saas_preflight.traction_control import (
    P12AuthorityPacket,
    PartnerTractionFacts,
    SignedTractionPlan,
    TractionAuthorityPins,
    TractionCheck,
    TractionClockRequest,
    TractionEvaluationBundle,
    TractionObservation,
    TractionPolicy,
    TractionReport,
    TractionSettlementEvidence,
    TractionTrustStore,
    SignedTractionClockAttestation,
)
from saas_preflight.verified_runner import (
    SignedAdvisorySnapshot,
    SignedRunnerImageAttestation,
    SignedVerifiedRunClockAttestation,
    SignedVerifiedRunnerConsumerClockAttestation,
    VerifiedCheckRecord,
    VerifiedCheckResult,
    VerifiedCheckSpec,
    VerifiedRunnerAttestation,
    VerifiedRunnerAuthorityPins,
    VerifiedRunnerChallenge,
    VerifiedRunnerConsumerClockRequest,
    VerifiedRunnerConsumptionReceipt,
    VerifiedRunnerEvidenceBundle,
    VerifiedRunnerImageIdentity,
    VerifiedRunnerPolicy,
    VerifiedRunnerRequirement,
    VerifiedRunnerTrustStore,
)


SCHEMA_MODELS = {
    "evaluated-model-route.schema.json": EvaluatedModelRoute,
    "model-router-policy.schema.json": ModelRouterPolicy,
    "model-routing-request.schema.json": ModelRoutingRequest,
    "model-routing-evaluation.schema.json": ModelRoutingEvaluation,
    "routine-task-definition.schema.json": RoutineTaskDefinition,
    "scheduled-routine-task.schema.json": ScheduledRoutineTask,
    "routine-task-execution.schema.json": RoutineTaskExecution,
    "human-activity-event.schema.json": HumanActivityEvent,
    "resource-usage-event.schema.json": ResourceUsageEvent,
    "role-labor-rate.schema.json": RoleLaborRate,
    "operational-cost-policy.schema.json": OperationalCostPolicy,
    "operations-activity-batch.schema.json": OperationsActivityBatch,
    "daily-derived-operations.schema.json": DailyDerivedOperations,
    "task-activity-coverage.schema.json": TaskActivityCoverage,
    "monthly-operating-tco.schema.json": MonthlyOperatingTco,
    "derived-operations-activity-summary.schema.json": DerivedOperationsActivitySummary,
    "verified-runner-challenge.schema.json": VerifiedRunnerChallenge,
    "verified-runner-consumer-clock-request.schema.json": VerifiedRunnerConsumerClockRequest,
    "signed-verified-runner-consumer-clock-attestation.schema.json": SignedVerifiedRunnerConsumerClockAttestation,
    "verified-runner-consumption-receipt.schema.json": VerifiedRunnerConsumptionReceipt,
    "verified-runner-image-identity.schema.json": VerifiedRunnerImageIdentity,
    "signed-runner-image-attestation.schema.json": SignedRunnerImageAttestation,
    "signed-advisory-snapshot.schema.json": SignedAdvisorySnapshot,
    "verified-check-spec.schema.json": VerifiedCheckSpec,
    "verified-check-result.schema.json": VerifiedCheckResult,
    "verified-check-record.schema.json": VerifiedCheckRecord,
    "signed-verified-run-clock-attestation.schema.json": SignedVerifiedRunClockAttestation,
    "verified-runner-requirement.schema.json": VerifiedRunnerRequirement,
    "verified-runner-trust-store.schema.json": VerifiedRunnerTrustStore,
    "verified-runner-policy.schema.json": VerifiedRunnerPolicy,
    "verified-runner-authority-pins.schema.json": VerifiedRunnerAuthorityPins,
    "verified-runner-attestation.schema.json": VerifiedRunnerAttestation,
    "verified-runner-evidence-bundle.schema.json": VerifiedRunnerEvidenceBundle,
    "source-policy.schema.json": SourcePolicy,
    "evidence-pointer.schema.json": EvidencePointer,
    "vendor-plan.schema.json": VendorPlan,
    "preview-page.schema.json": PreviewPage,
    "business-dossier.schema.json": BusinessDossier,
    "affiliate-decisions.schema.json": AffiliateDecisionBatch,
    "affiliate-partner-ledger.schema.json": AffiliatePartnerLedger,
    "demand-evidence.schema.json": DemandEvidence,
    "cohort-evidence.schema.json": CohortEvidence,
    "operations-evidence.schema.json": OperationsEvidence,
    "demand-summary-batch.schema.json": DemandSummaryBatch,
    "mangools-demand-safe-summary.schema.json": MangoolsDemandSafeSummary,
    "mangools-slate-demand-safe-summary.schema.json": MangoolsSlateDemandSafeSummary,
    "cohort-summary-batch.schema.json": CohortSummaryBatch,
    "operations-summary-batch.schema.json": OperationsSummaryBatch,
    "human-gold-set.schema.json": HumanGoldSet,
    "candidate-batch.schema.json": CandidateBatch,
    "gold-set-report.schema.json": GoldSetReport,
    "growth-identity.schema.json": GrowthIdentity,
    "metric-definition.schema.json": MetricDefinition,
    "semantic-fact.schema.json": SemanticFact,
    "semantic-snapshot.schema.json": SemanticSnapshot,
    "learning-gold-case.schema.json": LearningGoldCase,
    "learning-gold-set.schema.json": LearningGoldSet,
    "initial-learning-verification-key.schema.json": InitialLearningVerificationKey,
    "initial-learning-trust-store.schema.json": InitialLearningTrustStore,
    "initial-learning-quality-policy.schema.json": InitialLearningQualityPolicy,
    "initial-learning-dataset-profile.schema.json": InitialLearningDatasetProfile,
    "initial-learning-attestation.schema.json": InitialLearningAttestation,
    "initial-learning-quality-bundle.schema.json": InitialLearningQualityBundle,
    "initial-learning-quality-check.schema.json": InitialLearningQualityCheck,
    "initial-learning-quality-report.schema.json": InitialLearningQualityReport,
    "prompt-model-run.schema.json": PromptModelRun,
    "prompt-run-ledger.schema.json": PromptRunLedger,
    "initiative-proposal.schema.json": InitiativeProposal,
    "initiative-portfolio.schema.json": InitiativePortfolio,
    "initiative-assessment.schema.json": InitiativeAssessment,
    "policy-memo.schema.json": PolicyMemo,
    "human-policy-decision-receipt.schema.json": HumanPolicyDecisionReceipt,
    "content-brief.schema.json": ContentBrief,
    "editorial-article-input.schema.json": EditorialArticleInput,
    "human-editorial-numeric-field.schema.json": HumanEditorialNumericField,
    "category-expansion-input.schema.json": CategoryExpansionInput,
    "claim-evidence-link.schema.json": ClaimEvidenceLink,
    "editorial-draft.schema.json": EditorialDraft,
    "editorial-package.schema.json": EditorialPackage,
    "editorial-evaluation.schema.json": EditorialEvaluation,
    "content-derivative.schema.json": ContentDerivative,
    "derivative-bundle.schema.json": DerivativeBundle,
    "funnel-event.schema.json": FunnelEvent,
    "feedback-batch.schema.json": FeedbackBatch,
    "operations-kpi-input.schema.json": OperationsKpiInput,
    "kpi-scorecard.schema.json": KpiScorecard,
    "cta-health-input.schema.json": CtaHealthInput,
    "cta-health-evaluation.schema.json": CtaHealthEvaluation,
    "conditional-activation-input.schema.json": ConditionalActivationInput,
    "conditional-activation-evaluation.schema.json": ConditionalActivationEvaluation,
    "control-config.schema.json": ControlConfig,
    "scheduler-heartbeat.schema.json": SchedulerHeartbeat,
    "serving-lease.schema.json": ServingLease,
    "control-report.schema.json": ControlReport,
    "ed25519-verification-key.schema.json": Ed25519VerificationKey,
    "control-trust-store.schema.json": ControlTrustStore,
    "gold-report-attestation.schema.json": GoldReportAttestation,
    "release-decision-attestation.schema.json": ReleaseDecisionAttestation,
    "assurance-policy.schema.json": AssurancePolicy,
    "assurance-requirement.schema.json": AssuranceRequirement,
    "test-suite-facts.schema.json": TestSuiteFacts,
    "determinism-facts.schema.json": DeterminismFacts,
    "integrity-facts.schema.json": IntegrityFacts,
    "scan-facts.schema.json": ScanFacts,
    "review-facts.schema.json": ReviewFacts,
    "route-assurance-facts.schema.json": RouteAssuranceFacts,
    "assurance-evidence.schema.json": AssuranceEvidence,
    "assurance-evidence-bundle.schema.json": AssuranceEvidenceBundle,
    "local-assurance-report.schema.json": LocalAssuranceReport,
    "local-assurance-attestation.schema.json": LocalAssuranceAttestation,
    "public-release-approval-attestation.schema.json": PublicReleaseApprovalAttestation,
    "release-authorization.schema.json": ReleaseAuthorization,
    "release-assurance-report.schema.json": ReleaseAssuranceReport,
    "external-action-trust-store.schema.json": ExternalActionTrustStore,
    "external-action-policy.schema.json": ExternalActionPolicy,
    "external-action-target-rule.schema.json": ExternalActionTargetRule,
    "external-action-request.schema.json": ExternalActionRequest,
    "human-execution-approval.schema.json": HumanExecutionApproval,
    "controller-execution-grant.schema.json": ControllerExecutionGrant,
    "action-revocation.schema.json": ActionRevocation,
    "action-receipt.schema.json": ActionReceipt,
    "action-execution-claim.schema.json": ActionExecutionClaim,
    "action-journal-entry.schema.json": ActionJournalEntry,
    "action-journal-report.schema.json": ActionJournalReport,
    "measurement-trust-store.schema.json": MeasurementTrustStore,
    "measurement-authority-pins.schema.json": MeasurementAuthorityPins,
    "measurement-policy.schema.json": MeasurementPolicy,
    "measurement-rule-pins.schema.json": MeasurementRulePins,
    "fault-requirement.schema.json": FaultRequirement,
    "measurement-run-definition.schema.json": MeasurementRunDefinition,
    "signed-measurement-run-plan.schema.json": SignedMeasurementRunPlan,
    "producer-coverage.schema.json": ProducerCoverage,
    "coverage-partition.schema.json": CoveragePartition,
    "producer-attestation.schema.json": ProducerAttestation,
    "current-transaction.schema.json": CurrentTransaction,
    "demand-integrity-batch.schema.json": DemandIntegrityBatch,
    "payout-statement.schema.json": PayoutStatement,
    "cohort-integrity-batch.schema.json": CohortIntegrityBatch,
    "fault-exercise.schema.json": FaultExercise,
    "logical-job-run.schema.json": LogicalJobRun,
    "operations-integrity-batch.schema.json": OperationsIntegrityBatch,
    "measurement-bundle-index.schema.json": MeasurementBundleIndex,
    "measurement-bound-dossier.schema.json": MeasurementBoundDossier,
    "measurement-reconciliation-facts.schema.json": MeasurementReconciliationFacts,
    "measurement-integrity-report.schema.json": MeasurementIntegrityReport,
    "production-consumer-trust-store.schema.json": ProductionConsumerTrustStore,
    "production-consumer-policy.schema.json": ProductionConsumerPolicy,
    "production-consumer-clock-request.schema.json": ProductionConsumerClockRequest,
    "signed-production-consumer-clock-attestation.schema.json": SignedProductionConsumerClockAttestation,
    "production-authority-root-request.schema.json": ProductionAuthorityRootRequest,
    "signed-production-authority-roots.schema.json": SignedProductionAuthorityRoots,
    "provider-target-rule.schema.json": ProviderTargetRule,
    "production-consumption-request.schema.json": ProductionConsumptionRequest,
    "global-stop-snapshot.schema.json": GlobalStopSnapshot,
    "human-global-stop-reset.schema.json": HumanGlobalStopReset,
    "provider-dispatch-token.schema.json": ProviderDispatchToken,
    "provider-result-receipt.schema.json": ProviderResultReceipt,
    "provider-probe-receipt.schema.json": ProviderProbeReceipt,
    "production-consumption-result.schema.json": ProductionConsumptionResult,
    "production-integration-trust-store.schema.json": ProductionIntegrationTrustStore,
    "production-integration-policy.schema.json": ProductionIntegrationPolicy,
    "production-integration-requirement.schema.json": ProductionIntegrationRequirement,
    "production-integration-plan.schema.json": ProductionIntegrationPlan,
    "provider-conditional-mutation-facts.schema.json": ProviderConditionalMutationFacts,
    "provider-idempotency-retention-facts.schema.json": ProviderIdempotencyRetentionFacts,
    "provider-receipt-lookup-facts.schema.json": ProviderReceiptLookupFacts,
    "independent-readback-facts.schema.json": IndependentReadbackFacts,
    "kms-identity-separation-facts.schema.json": KmsIdentitySeparationFacts,
    "external-monotonic-anchor-facts.schema.json": ExternalMonotonicAnchorFacts,
    "trusted-clock-facts.schema.json": TrustedClockFacts,
    "shared-durable-store-fencing-facts.schema.json": SharedDurableStoreFencingFacts,
    "egress-allowlist-facts.schema.json": EgressAllowlistFacts,
    "backup-restore-facts.schema.json": BackupRestoreFacts,
    "rollback-disable-facts.schema.json": RollbackDisableFacts,
    "production-integration-evidence.schema.json": ProductionIntegrationEvidence,
    "production-integration-evidence-bundle.schema.json": ProductionIntegrationEvidenceBundle,
    "production-readiness-report.schema.json": ProductionReadinessReport,
    "production-tco-qa-attestation.schema.json": ProductionTcoQaAttestation,
    "production-human-environment-approval.schema.json": ProductionHumanEnvironmentApproval,
    "production-bootstrap-authorization.schema.json": ProductionBootstrapAuthorization,
    "production-readiness-authority-pins.schema.json": ProductionReadinessAuthorityPins,
    "production-reconciliation-facts.schema.json": ProductionReconciliationFacts,
    "production-reconciliation-record.schema.json": ProductionReconciliationRecord,
    "production-reconciliation-report.schema.json": ProductionReconciliationReport,
    "launch-artifact-component.schema.json": LaunchArtifactComponent,
    "launch-handoff-trust-store.schema.json": LaunchHandoffTrustStore,
    "launch-handoff-policy.schema.json": LaunchHandoffPolicy,
    "launch-handoff-requirement.schema.json": LaunchHandoffRequirement,
    "launch-handoff-plan.schema.json": LaunchHandoffPlan,
    "launch-gate-receipt.schema.json": LaunchGateReceipt,
    "launch-handoff-bundle.schema.json": LaunchHandoffBundle,
    "launch-handoff-report.schema.json": LaunchHandoffReport,
    "launch-semantic-scope.schema.json": LaunchSemanticScope,
    "rights-semantic-packet.schema.json": RightsSemanticPacket,
    "affiliate-semantic-packet.schema.json": AffiliateSemanticPacket,
    "measurement-semantic-packet.schema.json": MeasurementSemanticPacket,
    "gold-semantic-packet.schema.json": GoldSemanticPacket,
    "production-semantic-packet.schema.json": ProductionSemanticPacket,
    "deployment-readiness-record.schema.json": DeploymentReadinessRecord,
    "publication-readiness-record.schema.json": PublicationReadinessRecord,
    "deployment-publication-semantic-packet.schema.json": DeploymentPublicationSemanticPacket,
    "launch-semantic-packet.schema.json": LaunchSemanticPacket,
    "launch-semantic-authority-pins.schema.json": LaunchSemanticAuthorityPins,
    "launch-semantic-component.schema.json": LaunchSemanticComponent,
    "launch-semantic-gate-evaluation.schema.json": LaunchSemanticGateEvaluation,
    "launch-semantic-evaluation.schema.json": LaunchSemanticEvaluation,
    "settlement-amendment-trust-store.schema.json": SettlementAmendmentTrustStore,
    "settlement-amendment-policy.schema.json": SettlementAmendmentPolicy,
    "settlement-amendment-authority-pins.schema.json": SettlementAmendmentAuthorityPins,
    "original-settlement-binding.schema.json": OriginalSettlementBinding,
    "partner-settlement-amount.schema.json": PartnerSettlementAmount,
    "settlement-status-change.schema.json": SettlementStatusChange,
    "settlement-payout-adjustment.schema.json": SettlementPayoutAdjustment,
    "signed-settlement-amendment.schema.json": SignedSettlementAmendment,
    "settlement-completeness-coverage.schema.json": SettlementCompletenessCoverage,
    "settlement-completeness-attestation.schema.json": SettlementCompletenessAttestation,
    "settlement-amendment-evaluation.schema.json": SettlementAmendmentEvaluation,
    "traction-trust-store.schema.json": TractionTrustStore,
    "traction-policy.schema.json": TractionPolicy,
    "traction-authority-pins.schema.json": TractionAuthorityPins,
    "traction-clock-request.schema.json": TractionClockRequest,
    "signed-traction-clock-attestation.schema.json": SignedTractionClockAttestation,
    "signed-traction-plan.schema.json": SignedTractionPlan,
    "p12-authority-packet.schema.json": P12AuthorityPacket,
    "partner-traction-facts.schema.json": PartnerTractionFacts,
    "traction-observation.schema.json": TractionObservation,
    "traction-settlement-evidence.schema.json": TractionSettlementEvidence,
    "traction-evaluation-bundle.schema.json": TractionEvaluationBundle,
    "traction-check.schema.json": TractionCheck,
    "traction-report.schema.json": TractionReport,
    "repository-file-digest.schema.json": RepositoryFileDigest,
    "repository-verification-fact.schema.json": RepositoryVerificationFact,
    "repository-verification-attestation.schema.json": RepositoryVerificationAttestation,
    "repository-verification-requirement.schema.json": RepositoryVerificationRequirement,
    "repository-verification-evidence-bundle.schema.json": RepositoryVerificationEvidenceBundle,
    "repository-candidate-manifest.schema.json": RepositoryCandidateManifest,
    "repository-acceptance-trust-store.schema.json": RepositoryAcceptanceTrustStore,
    "repository-acceptance-policy.schema.json": RepositoryAcceptancePolicy,
    "repository-acceptance-receipt-chain.schema.json": RepositoryAcceptanceReceiptChain,
    "repository-acceptance-authority-pins.schema.json": RepositoryAcceptanceAuthorityPins,
    "repository-acceptance-authority-bundle.schema.json": RepositoryAcceptanceAuthorityBundle,
    "human-repository-acceptance.schema.json": HumanRepositoryAcceptance,
    "repository-acceptance-report.schema.json": RepositoryAcceptanceReport,
}


def export_schemas(output_dir: Path) -> tuple[Path, ...]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for filename, model in SCHEMA_MODELS.items():
        destination = output_dir / filename
        serialized = json.dumps(
            model.model_json_schema(mode="validation"),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        destination.write_text(serialized + "\n", encoding="utf-8")
        written.append(destination)
    return tuple(written)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("schemas"),
        help="Directory for generated *.schema.json files (default: schemas)",
    )
    args = parser.parse_args()
    export_schemas(args.output_dir)


if __name__ == "__main__":
    main()
